### ISSUE TITLE
mussync-tools: does not detect application/octect-stream audio files

### ISSUE THREAD

**Issue by xrat** [biapy/howto.biapy.com#4]
I wanted to use mussync-tools v1.4.10 but it does not recognize my mp3 files:
```
$ mussync-tools -i "mussync test" -o output/ --output-format=ogg -q 6 --copy-all
 * Processing folder /data/mussync test...
   - 01__what_s_going_on.mp3 is not a audio file... Skipping.
```
Apparently, this is because `file` provides the following:
```
$ file --brief --mime-type mussync\ test/01__what_s_going_on.mp3
application/octet-stream
$ file --brief mussync\ test/01__what_s_going_on.mp3
Audio file with ID3 version 2.3.0
```
I am using Ubuntu 14.04 with `file` 5.14.
I have hacked the script to remove `--mime-type` from the `file` command, and I changed the test for the audio type to `[[ ${input_file_mimetype,,} != *audio* ]]`. mussync-tools then proceeds with the conversion.

**Comment by landure** [comment]
Hi,

thank you for the solution. It is now added to mussync-tools v1.5.0.
