### ISSUE TITLE
mussync-tools: quality setting with -q ignored

### ISSUE THREAD

**Issue by xrat** [biapy/howto.biapy.com#5]
I am using mussync-tools v1.4.10 with `--output-format=ogg`. Apparently, `-q #` is ignored whereas `--quality=#` works as expected.

**Comment by landure** [comment]
Hi

the bug is fixed in mussync-tools v1.5.0. It was due to an missing support for the documented optional argument notation . in certain conditions.

**Comment by xrat** [comment]
Thanks. I can confirm that it works with `-q #` now on my system (Lubuntu 14.04).
