### ISSUE TITLE
Feature request: support for opus and m4a

### ISSUE THREAD

**Issue by emk2203** [biapy/howto.biapy.com#6]
Could you also support the conversion to **opus** and **m4a** including metadata and album art? m4a is widespread, and opus certainly going to be the successor for ogg. The structure for opus and ogg in regards to metadata is equal, so not much effort would be needed. For m4a, I use the following myself

```
#!/bin/bash

# Script to convert FLAC files​ ​to​ m4a, keeping tags and album art​
# relies on avconv (standard for Raspbian) instead of ffmpeg
# depends on: avconv, avprobe, flac, fdkaac, libfdk_aac, AtomicParsley
# fdkaac and libfdk_aac need to be compiled from source (​github)​
for i in *.flac; do

avconv -i "$i" -an "${i[@]/flac/jpeg}"
avprobe -v 0 -show_format -of json "$i" > "${i[@]/flac/json}"
flac -sdc "$i" | fdkaac - -o "${i[@]/%flac/m4a}" -p2 -m5 -a1 --tag-from-json="${i[@]/flac/json}"?format.tags
AtomicParsley "${i[@]/flac/m4a}" --artwork "${i[@]/flac/jpeg}" --overWrite
rm "${i[@]/flac/jpeg}" "${i[@]/flac/json}"
done
```
as a quick-and-dirty version which could be of use maybe.

**Comment by landure** [comment]
Hi,

thank you for the code. mussync-tools v1.5.0 now has support for aac m4a files. I did not do the work for opus because i'm short on time, but half of the feature request is done, so i'm closing it.
